// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC-M0scSNR3-vkc5ckrCpr9-KYzXLBRok',
    appId: '1:482608399970:web:bd4001c0541d1b87bb333b',
    messagingSenderId: '482608399970',
    projectId: 'ecommerce-app-fake-api',
    authDomain: 'ecommerce-app-fake-api.firebaseapp.com',
    storageBucket: 'ecommerce-app-fake-api.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZj7c2bbzXhEFMf3_UR9vbk3wpFyz0haI',
    appId: '1:482608399970:android:f56808dcaebb6cf0bb333b',
    messagingSenderId: '482608399970',
    projectId: 'ecommerce-app-fake-api',
    storageBucket: 'ecommerce-app-fake-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRtPmLGvhfPNh4B7F4PTIJmcLRrVI2zWQ',
    appId: '1:482608399970:ios:d08c5a303fd45323bb333b',
    messagingSenderId: '482608399970',
    projectId: 'ecommerce-app-fake-api',
    storageBucket: 'ecommerce-app-fake-api.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRtPmLGvhfPNh4B7F4PTIJmcLRrVI2zWQ',
    appId: '1:482608399970:ios:d08c5a303fd45323bb333b',
    messagingSenderId: '482608399970',
    projectId: 'ecommerce-app-fake-api',
    storageBucket: 'ecommerce-app-fake-api.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC-M0scSNR3-vkc5ckrCpr9-KYzXLBRok',
    appId: '1:482608399970:web:dd69989cc684d02fbb333b',
    messagingSenderId: '482608399970',
    projectId: 'ecommerce-app-fake-api',
    authDomain: 'ecommerce-app-fake-api.firebaseapp.com',
    storageBucket: 'ecommerce-app-fake-api.firebasestorage.app',
  );

}